name: bones_ui_app_example
description: A Bones_UI Web App example.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  bones_ui: ^2.0.3
  bones_ui_bootstrap: ^2.0.3
  intl_messages: ^2.0.1
  async_field: ^1.0.4
  bootstrap_sass: ^4.5.0

dev_dependencies:
  build_runner: ^2.0.6
  build_web_compilers: ^3.0.0
  pedantic: ^1.11.0
  sass_builder: ^2.1.3
  test: ^1.16.0

#dependency_overrides:
#  bones_ui:
#    path: ../bones_ui
#  bones_ui_bootstrap:
#    path: ../bones_ui_bootstrap
#  dom_builder:
#    path: ../dom_builder
#  async_field:
#    path: ../async_field
#  swiss_knife:
#    path: ../swiss_knife