name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Dart version
        run: |
          dart --version
          uname -a
      - name: Install dependencies
        run: dart pub get
      - name: dart format
        run: dart format -o none --set-exit-if-changed .
      - name: dart analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: dependency_validator
        run: dart run dependency_validator
      - name: Run tests
        run: dart test

  build_backend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend-example

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Dart version
        run: |
          dart --version
          uname -a
      - name: Install dependencies
        run: dart pub get
      - name: dart format
        run: dart format -o none --set-exit-if-changed .
      - name: dart analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Run tests
        run: dart test
