name: backend_example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  bones_api: ^1.0.2

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0

#dependency_overrides:
#  bones_api:
#    path: ../../bones_api